In [1]:
# importing all necessary libraries
import pandas as pd
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer
#setting max width to show all columns in dataframe
pd.set_option('max_colwidth', 100)

df = pd.read_csv("C:\\Users\\Shubham\\Desktop\\Leader Merge File.csv")
df.head(136000)

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Tweet Id,Text,Subjectivity,Polarity,score,leader
0,0,0,0.0,1.600000e+18,Removal of Article 370 ended corruption in J&amp;K. SC should dismiss all the application ...,0.000000,0.000000,Neutral,amit
1,1,1,1.0,1.600000e+18,Invasion can be quite mischievous. Do people use such colors for common use? Love Jihad...,0.700000,0.060000,Positive,amit
2,2,2,2.0,1.600000e+18,Supreme Court is going to start hearing on Article 370 &amp; 35 A. Would Supreme Court of India ...,0.000000,0.000000,Neutral,amit
3,3,3,3.0,1.600000e+18,Article 370 was Abrogated and many Progressive Central Laws were extended to JK but on the grou...,0.375000,0.250000,Positive,amit
4,4,4,4.0,1.600000e+18,POK liya bjp ne ?\nAksai chin liya?\nBhai Congress ke Negative points pata hai.. Bjp ke posit...,0.542424,-0.034545,Negative,amit
...,...,...,...,...,...,...,...,...,...
135995,135995,18243,1801.0,1.010000e+18,"Ji,\n\nIt will be cheating to nation if SardarPatels...",0.375000,0.062500,Positive,yogi
135996,135996,18244,1802.0,1.010000e+18,In the run-up to the state assembly polls in 2014...,0.000000,0.000000,Neutral,yogi
135997,135997,18245,1803.0,1.010000e+18,Storey of Jammu betrayal. \n\nIn the run-up to th...,0.000000,0.000000,Neutral,yogi
135998,135998,18246,1804.0,1.010000e+18,"Ji,\n\nIt will be cheating to nation if SardarP...",0.375000,0.062500,Positive,yogi
135999,135999,18247,1805.0,1.010000e+18,"Is there any step taken for population control in last 4years,is there for shri Ram man...",0.066667,0.000000,Neutral,yogi

In [2]:
vectorizer = CountVectorizer()
bow_model = vectorizer.fit_transform(df)
print(bow_model)  # returns the rows and column number of cells which have 1 as value

  (0, 7)	1
  (1, 7)	1
  (2, 7)	1
  (3, 6)	1
  (3, 0)	1
  (4, 5)	1
  (5, 4)	1
  (6, 2)	1
  (7, 3)	1
  (8, 1)	1

In [3]:
# print the full sparse matrix
print(bow_model.toarray())

[[0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0]]

In [15]:
df_bow = pd.DataFrame(bow_model.toarray(), columns = vectorizer.vocabulary_.keys())
df_bow

   unnamed  tweet  id  text  subjectivity  polarity  score  leader
0        0      0   0     0             0         0      0       1
1        0      0   0     0             0         0      0       1
2        0      0   0     0             0         0      0       1
3        1      0   0     0             0         0      1       0
4        0      0   0     0             0         1      0       0
5        0      0   0     0             1         0      0       0
6        0      0   1     0             0         0      0       0
7        0      0   0     1             0         0      0       0
8        0      1   0     0             0         0      0       0

In [ ]:
# df_bow.to_csv("C:\\Users\\Shubham\\Desktop\\bow.csv")

In [17]:
df_bow.to_csv("C:\\Users\\Shubham\\Desktop\\bowww.csv", index=False)